# Generated by Django 2.1.2 on 2019-02-04 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20181223_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='post_user',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
